{
 "title": "Substreams",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Responses Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(deployment_substreams_blockstream_responses[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Connect Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "deployment_substreams_blockstream_connect_duration"
    }
   ]
  },
  {
   "title": "Stream Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(deployment_substreams_blockstream_restarts[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Time Between Responses Distribution (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(deployment_substreams_blockstream_time_between_responses_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}